1----

SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER employee_salary_audit
AFTER INSERT OR UPDATE OR DELETE ON EMPLOYEE
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        DBMS_OUTPUT.PUT_LINE('Inserted Salary: ' || :NEW.SALARY);
    ELSIF UPDATING THEN
        DBMS_OUTPUT.PUT_LINE('Old Salary: ' || :OLD.SALARY || ', New Salary: ' || :NEW.SALARY);
        DBMS_OUTPUT.PUT_LINE('Salary Difference: ' || (:NEW.SALARY - :OLD.SALARY));
    ELSIF DELETING THEN
        DBMS_OUTPUT.PUT_LINE('Deleted Salary: ' || :OLD.SALARY);
    END IF;
END;
/




2---
INSERT INTO EMPLOYEE VALUES (101, 'Jane', 30,'IT',45000);


3---
UPDATE EMPLOYEE
SET SALARY = 50000
WHERE ID = 1;


4---
DELETE FROM EMPLOYEE
WHERE ID = 1;


5---
CREATE OR REPLACE TRIGGER employee_name_uppercase
BEFORE INSERT OR UPDATE ON EMPLOYEE
FOR EACH ROW
BEGIN
    :NEW.NAME := UPPER(:NEW.NAME);
END;
/

INSERT INTO EMPLOYEE 
VALUES (102, 'Rakesh', 32,'Raipur',80000);

SELECT NAME 
FROM EMPLOYEE 
WHERE ID = 102;
